# Criação de um ARRAY

In [8]:
import numpy as np
#Criando um array1 

lista1 = [1, 2, 3, 4, 5]
array1 = np.array(lista1)
print(array1)
print(type(array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#criando um array2

lista2 = [6, 7, 8, 9, 10]
array2 = np.array(lista2)
print(array2)
print(type(array2))

[ 6  7  8  9 10]
<class 'numpy.ndarray'>


# Operações Matemáticas

In [15]:
result = array1 + array2
print(result)
print(type(result))

[ 7  9 11 13 15]
<class 'numpy.ndarray'>


# Indexação e Slicing
## Indexação: Refere-se ao acesso a elementos individuais em um array ou matriz. Em Numpy, vpcẽ pode acessar um elemento usando a notação de colchetes. Por exemplo, array[2] acessa o terceiro elemento de um array.
## Slicing: É a prática de extrair um subconjunto de elementos de um array. Você pode especificar um intervalo de índices. Por exemplo, array[1:4] retornará os elementos do índice 1 ao 3.  

In [14]:
#Acesso pela indexação
print(array2[3])
print(array1[3])
print(result[3])

9
4
13


In [24]:
#Extraindo elemento via Slicing
slice = array1[2:3]
print(slice)
print(array1[2:4])
print(array1[2:5])
print(array2[2:6]) #No caso são só [0 - 1 - 2 - 3 - 4] cinco valores ao total
print(array2[2:5])
print(array2[0:5]) #Aqui mostra todos os valores

[3]
[3 4]
[3 4 5]
[ 8  9 10]
[ 8  9 10]
[ 6  7  8  9 10]


# Funções Estatísticas

In [27]:
# Gerar uma lista aleatória de 10 números reais entre 0 e 10
lista_aleatoria = np.random.uniform(0, 10, 10)

# Arredondar para 2 casas decimais
lista_aleatoria = np.round(lista_aleatoria, 2)

print(lista_aleatoria)

[6.99 7.36 9.8  0.69 5.64 9.67 1.42 5.52 7.94 4.23]


In [29]:
#01 - np.mean(): Calcula a média aritmética dos valores, representando o valor central de um conjunto de dados.
media = np.mean(lista_aleatoria)
print(media)

5.926


In [31]:
#02 - np.median(): Encontra o valor central em um conjunto de dados, dividindo a lista em duas partes iguais.
valor_central = np.median(lista_aleatoria)
print(valor_central)

6.3149999999999995


In [32]:
#03 - np.std(): Mede a dispersão dos dados em relação à média, indicando quanto os valores variam.
dispersao = np.std(lista_aleatoria)
print(dispersao)

2.9514884380596853


In [33]:
#04 - np.var(): Calcula a variância, que é a média dos quadrados das diferenças em relação à média.
variancia = np.var(lista_aleatoria)
print(variancia)

8.711284000000001


In [34]:
#05 - np.min(): Retorna o menor valor do array, ajudando a identificar o ponto mais baixo dos dados.
menor = np.min(lista_aleatoria)
print(menor)

0.69


In [36]:
#06 - np.max(): Retorna o maior valor do array, identificando o ponto mais alto dos dados.
maior = np.max(lista_aleatoria)
print(maior)

9.8


# Mascara Booleana no Numpy

##### Uma máscara booleana é uma estrutura de dados (geralmente um array ou série) que contém valores booleanos (True ou False). No contexto do NumPy ou Pandas, é usada para filtrar ou selecionar elementos de um array ou DataFrame com base em uma condição específica.

In [41]:
# Criando um array de números
array = np.array([5, 10, 15, 20, 25])

# Criando uma máscara booleana para selecionar elementos maiores que 15
mascara = array > 15

# Aplicando a máscara para filtrar o array
resultado = array[mascara]

print("Array original:", array)
print("Máscara booleana:", mascara)
print("Elementos maiores que 15:", resultado)


Array original: [ 5 10 15 20 25]
Máscara booleana: [False False False  True  True]
Elementos maiores que 15: [20 25]


In [42]:
# Modificação de elementos 
array[array < 15] = 0  # Altera elementos menores que 15 para 0
print(array)

[ 0  0 15 20 25]


In [46]:
# Contagem de elementos
count = np.sum(array >= 15)
print(count)
count = np.sum(array > 15)
print(count)

3
2


In [49]:
# Combinação de condições
mask = (array > 10) & (array < 20)
print(mask)
print(array[mask])

[False False  True False False]
[15]
